name: tokopedia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0-329.0.dev <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.3.2
  cupertino_icons: ^1.0.2
  external_app_launcher: ^3.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.7
  get: 4.6.5
  intl_phone_number_input: ^0.7.2
  pinput: ^2.2.23
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  google_sign_in: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/image/
