// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLnvw1JSjsItoOS6xn1PRZ2jAyWkOzfEY',
    appId: '1:419084311118:web:e84cd0273a35ade7dc011f',
    messagingSenderId: '419084311118',
    projectId: 'tokopedia-a1a1a',
    authDomain: 'tokopedia-a1a1a.firebaseapp.com',
    storageBucket: 'tokopedia-a1a1a.appspot.com',
    measurementId: 'G-4XYPG9JGYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzP8UrWDQxXugVKSPOapm9fdQa0Gy744',
    appId: '1:419084311118:android:80d288008bfebad7dc011f',
    messagingSenderId: '419084311118',
    projectId: 'tokopedia-a1a1a',
    storageBucket: 'tokopedia-a1a1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwp2pZpzbGb_RhXKrdHrnkbcQfivA9bp4',
    appId: '1:419084311118:ios:bfc146ea1dd55d48dc011f',
    messagingSenderId: '419084311118',
    projectId: 'tokopedia-a1a1a',
    storageBucket: 'tokopedia-a1a1a.appspot.com',
    iosClientId: '419084311118-a1iflaesne9iq8k3996lukred3ulrns5.apps.googleusercontent.com',
    iosBundleId: 'com.tokopedia.tokopedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwp2pZpzbGb_RhXKrdHrnkbcQfivA9bp4',
    appId: '1:419084311118:ios:bfc146ea1dd55d48dc011f',
    messagingSenderId: '419084311118',
    projectId: 'tokopedia-a1a1a',
    storageBucket: 'tokopedia-a1a1a.appspot.com',
    iosClientId: '419084311118-a1iflaesne9iq8k3996lukred3ulrns5.apps.googleusercontent.com',
    iosBundleId: 'com.tokopedia.tokopedia',
  );
}
